import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parse } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const YAML_PATH = resolve(ROOT, "config/site.yaml");
const CSS_PATH = resolve(ROOT, "src/generated/theme.css");

async function loadSchema() {
  const mod = await import(
    pathToFileURL(resolve(ROOT, "config/schema.ts")).href
  );
  return mod.siteConfigSchema;
}

function buildThemeCss(cfg) {
  const lightBlock = [
    ":root,",
    ":root[data-theme='light'] {",
    `  --color-bg: ${cfg.theme.background};`,
    `  --color-primary: ${cfg.theme.primary};`,
    `  --color-secondary: ${cfg.theme.secondary};`,
    `  --color-accent: ${cfg.theme.accent};`,
    `  --card-radius: ${cfg.card.radius};`,
    `  --card-blur: ${cfg.card.blur};`,
    `  --card-border-opacity: ${cfg.card.border_opacity};`,
    `  --card-bg-opacity: ${cfg.card.bg_opacity};`,
    "}",
  ].join("\n");

  const darkBlock = [
    ":root[data-theme='dark'] {",
    `  --color-bg: ${cfg.dark.background};`,
    `  --color-primary: ${cfg.dark.primary};`,
    `  --color-secondary: ${cfg.dark.secondary};`,
    `  --color-accent: ${cfg.dark.accent};`,
    "}",
  ].join("\n");

  return `/* AUTO-GENERATED by scripts/build-theme.mjs — DO NOT EDIT */\n${lightBlock}\n\n${darkBlock}\n`;
}

async function main() {
  const schema = await loadSchema();
  const raw = readFileSync(YAML_PATH, "utf8");
  const parsed = parse(raw);
  const result = schema.safeParse(parsed);
  if (!result.success) {
    console.error("[build-theme] Schema validation failed:");
    console.error(result.error.format());
    process.exit(1);
  }
  const css = buildThemeCss(result.data);
  mkdirSync(dirname(CSS_PATH), { recursive: true });
  writeFileSync(CSS_PATH, css, "utf8");
  console.log(`[build-theme] Wrote ${CSS_PATH}`);
}

main().catch((err) => {
  console.error("[build-theme]", err);
  process.exit(1);
});
